### PR TITLE
Fix template generator for ToString method

### LINKED ISSUE #278: Build warnings for XML documentation comments
### Describe the bug

Generating Value Objects in a project that has the `GenerateDocumentationFile` option set to `true` in the project file creates multiple warnings during build:

```
CustomerId.g.cs(146,27): Warning CS1584 : XML comment has syntactically incorrect cref attribute '{item.UnderlyingTypeFullName}.ToString()'
CustomerId.g.cs(146,27): Warning CS1658 : Identifier expected. See also error CS1001.
CustomerId.g.cs(146,28): Warning CS1658 : Type parameter declaration must be an identifier not a type. See also error CS0081.
```

Looking into the warning a bit more - looks like a template isn't being expanded properly in the source generator for the `ToString()` method. The following is from the generated file for the example at the start of the README (`CustomerId`):
```c#
/// <inheritdoc cref="{item.UnderlyingTypeFullName}.ToString()" />
public readonly override global::System.String ToString() => Value.ToString();
```

### Steps to reproduce

1. Create a new project from the class library template
2. Install Vogen (version 3.0.3)
3. Replace `Class1` with the `CustomerId` example from the README:
``` c#
[ValueObject]
public partial struct CustomerId {
    // optional
    private static Validation Validate(int value) => value > 0 
        ? Validation.Ok 
        : Validation.Invalid("Customer IDs must be a positive number.");
}
```
4. Add `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to the csproj `PropertyGroup`
5. Run `dotnet build`

### Expected behaviour

Source generator should not introduce warnings

### PR DESCRIPTION
**Pull request by bradtglass**
Fixes #278 

This PR fixes a broken string interpolation which made the XML doc comment for the generated `ToString()` method invalid.

This change affects pretty much every snapshot so the changes are huge unfortunately. I've broken the PR into two commits - the first is the fix, the second is the snapshot updates

### CODE REVIEW

**Comment by SteveDunn** [comment]
Looks good to me! Thanks for spotting!

File: src/Vogen/Util.cs [hunk 1]
```diff
@@ -198,7 +198,7 @@ public static string GenerateDebuggerProxyForClasses(TypeDeclarationSyntax tds,
 
     public static string GenerateToStringReadOnly(VoWorkItem item) =>
         item.HasToString ? string.Empty :
-            @"/// <summary>Returns the string representation of the underlying type</summary>
+            $@"/// <summary>Returns the string representation of the underlying type</summary>
```
Comment (SteveDunn) [inline src/Vogen/Util.cs:201]: Well spotted! 👍

**Review by SteveDunn — APPROVED** [review]
