### PR TITLE
Fix: System.Text.Json factories fail to generate if assembly name has hyphens

### LINKED ISSUE #717: Vogen generates invalid namespace in SystemTextJsonConverterFactory_g.cs
### Describe the bug

It seems that when a namespace contains a hyphen ( - ), an invalid namespace is generated in the file SystemTextJsonConverterFactory_g.cs. The namespace "CRM_API" ends up being "CRM - API".

The namespace is however correct in the value-object's generated partial struct.

### Steps to reproduce

1. Download the following project https://github.com/Healios/vogen-namespace-error
2. Build it

### Expected behaviour

I was expecting the namespace to be "CRM_API".

### PR DESCRIPTION
**Pull request by SteveDunn**
Fixes #717

### CODE REVIEW

File: samples/WebApplication/Program.cs [hunk 1]
```diff
@@ -26,7 +26,7 @@
     // the following extension method is available if you specify `GenerateSwashbuckleMappingExtensionMethod` - as shown above
     
     opt.MapVogenTypesInWebApplication();
-    opt.MapVogenTypesInWebApplicationShared();
```
Comment (SteveDunn) [inline samples/WebApplication/Program.cs:29]: Previously, if the project named contained dots, then these would be stripped out, but now they're replaced with `_`. This was part of a bug fix for something else that derived the namespace from the project but failed where the project contained hyphens.
